### ISSUE TITLE
Version 0.3.1 fails to build on node 0.10

### ISSUE THREAD

**Issue by thaumant** [mcavage/node-bunyan-syslog#33]
```
$ uname -srp
Linux 2.6.32-042stab104.1 x86_64
$ node -v
v0.10.36
```

```
$ npm i bunyan-syslog@0.3.1
npm WARN package.json test@0.0.0 No description
npm WARN package.json test@0.0.0 No repository field.
npm WARN package.json test@0.0.0 No README data
npm http GET https://registry.npmjs.org/bunyan-syslog/0.3.1
npm http 200 https://registry.npmjs.org/bunyan-syslog/0.3.1
npm http GET https://registry.npmjs.org/bunyan-syslog/-/bunyan-syslog-0.3.1.tgz
npm http 200 https://registry.npmjs.org/bunyan-syslog/-/bunyan-syslog-0.3.1.tgz

> bunyan-syslog@0.3.1 install /home/thaumant/test/node_modules/bunyan-syslog
> node-gyp rebuild

make: Entering directory `/home/thaumant/test/node_modules/bunyan-syslog/build'
  CXX(target) Release/obj.target/syslog/src/syslog.o
In file included from ../src/syslog.cc:7:0:
../../nan/nan.h:328:47: error: 'REPLACE_INVALID_UTF8' is not a member of 'v8::String'
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
make: *** [Release/obj.target/syslog/src/syslog.o] Error 1
make: Leaving directory `/home/thaumant/test/node_modules/bunyan-syslog/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab104.1
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/thaumant/test/node_modules/bunyan-syslog
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

Version 0.3.0 builds successfully.

**Comment by ziir** [comment]
I'm having the same issue on a regular basis, working around it by :

- ensuring `npm` is at `latest-2` tag while installing / rebuilding
(Though it's probably more linked to the `node-gyp` version ?)

```
npm install -g npm@latest-2
npm rebuild bunyan-syslog
```

Thanks for the work :)
