### ISSUE TITLE
Can't build on node v0.12 OS X 10.10.2

### ISSUE THREAD

**Issue by alx13** [mcavage/node-bunyan-syslog#17]
```
$ npm install bunyan-syslog
-
> bunyan-syslog@0.2.2 install /Users/alx13/Git/temp2/node_modules/bunyan-syslog
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/syslog/src/syslog.o
../src/syslog.cc:57:26: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Open(const Arguments& args) {
                         ^~~~~~~~~
                         v8::internal::Arguments
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/syslog.cc:58:14: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/syslog.cc:60:2: error: member access into incomplete type 'const v8::internal::Arguments'
        REQUIRE_STRING_ARG(args, 0, ident);
        ^
../src/syslog.cc:34:2: note: expanded from macro 'REQUIRE_STRING_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^
../src/syslog.cc:23:10: note: expanded from macro 'REQUIRE_ARGS'
        if (ARGS.Length() == 0)                                 \
                ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:60:2: error: no member named 'New' in 'v8::String'
        REQUIRE_STRING_ARG(args, 0, ident);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:34:2: note: expanded from macro 'REQUIRE_STRING_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^~~~~~~~~~~~~~~~~~
../src/syslog.cc:24:3: note: expanded from macro 'REQUIRE_ARGS'
                RETURN_ARGS_EXCEPTION("missing arguments");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:60:2: error: member access into incomplete type 'const v8::internal::Arguments'
../src/syslog.cc:35:10: note: expanded from macro 'REQUIRE_STRING_ARG'
        if (ARGS.Length() <= (I) || !ARGS[I]->IsString())               \
                ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:60:2: error: no member named 'New' in 'v8::String'
        REQUIRE_STRING_ARG(args, 0, ident);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:36:3: note: expanded from macro 'REQUIRE_STRING_ARG'
                RETURN_ARGS_EXCEPTION("argument " #I " must be a String"); \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:60:2: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        REQUIRE_STRING_ARG(args, 0, ident);
        ^                  ~~~~  ~
../src/syslog.cc:37:28: note: expanded from macro 'REQUIRE_STRING_ARG'
        String::Utf8Value VAR(ARGS[I]->ToString());
                                  ^
../src/syslog.cc:61:2: error: member access into incomplete type 'const v8::internal::Arguments'
        REQUIRE_INT_ARG(args, 1, logopt);
        ^
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^
../src/syslog.cc:23:10: note: expanded from macro 'REQUIRE_ARGS'
        if (ARGS.Length() == 0)                                 \
                ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:61:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 1, logopt);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^~~~~~~~~~~~~~~~~~
../src/syslog.cc:24:3: note: expanded from macro 'REQUIRE_ARGS'
                RETURN_ARGS_EXCEPTION("missing arguments");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:61:2: error: member access into incomplete type 'const v8::internal::Arguments'
../src/syslog.cc:28:10: note: expanded from macro 'REQUIRE_INT_ARG'
        if (ARGS.Length() <= (I) || !ARGS[I]->IsNumber())               \
                ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:61:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 1, logopt);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:29:3: note: expanded from macro 'REQUIRE_INT_ARG'
                RETURN_ARGS_EXCEPTION("argument " #I " must be an Integer"); \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:61:2: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        REQUIRE_INT_ARG(args, 1, logopt);
        ^               ~~~~  ~
../src/syslog.cc:30:30: note: expanded from macro 'REQUIRE_INT_ARG'
        Local<Integer> _ ## VAR(ARGS[I]->ToInteger());                  \
                                    ^
../src/syslog.cc:62:2: error: member access into incomplete type 'const v8::internal::Arguments'
        REQUIRE_INT_ARG(args, 2, facility);
        ^
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^
../src/syslog.cc:23:10: note: expanded from macro 'REQUIRE_ARGS'
        if (ARGS.Length() == 0)                                 \
                ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:62:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 2, facility);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:27:2: note: expanded from macro 'REQUIRE_INT_ARG'
        REQUIRE_ARGS(ARGS);                                             \
        ^~~~~~~~~~~~~~~~~~
../src/syslog.cc:24:3: note: expanded from macro 'REQUIRE_ARGS'
                RETURN_ARGS_EXCEPTION("missing arguments");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:62:2: error: member access into incomplete type 'const v8::internal::Arguments'
../src/syslog.cc:28:10: note: expanded from macro 'REQUIRE_INT_ARG'
        if (ARGS.Length() <= (I) || !ARGS[I]->IsNumber())               \
                ^
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/syslog.cc:62:2: error: no member named 'New' in 'v8::String'
        REQUIRE_INT_ARG(args, 2, facility);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:29:3: note: expanded from macro 'REQUIRE_INT_ARG'
                RETURN_ARGS_EXCEPTION("argument " #I " must be an Integer"); \
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/syslog.cc:14:53: note: expanded from macro 'RETURN_ARGS_EXCEPTION'
        return ThrowException(Exception::TypeError(String::New(MSG)))
                                                   ~~~~~~~~^
../src/syslog.cc:62:2: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        REQUIRE_INT_ARG(args, 2, facility);
        ^               ~~~~  ~
../src/syslog.cc:30:30: note: expanded from macro 'REQUIRE_INT_ARG'
        Local<Integer> _ ## VAR(ARGS[I]->ToInteger());                  \
                                    ^
../src/syslog.cc:66:10: error: no matching function for call to 'Undefined'
        return (Undefined());
                ^~~~~~~~~
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single
      argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/syslog.cc:70:25: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Log(const Arguments& args) {
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/alx13/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/syslog/src/syslog.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alx13/Git/temp2/node_modules/bunyan-syslog
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "bunyan-syslog"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bunyan-syslog@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bunyan-syslog@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bunyan-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bunyan-syslog
npm ERR! There is likely additional logging output above.
```

```
$ npm version
{ npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

**Comment by mcavage** [comment]
You need the $HEAD version ,which was just published as 0.3.0.

**Comment by alx13** [comment]
Thanks!
